/* Node.js >=18; no packages required. */
const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../src/core.js');
const make=()=>C.newDoc('A diagram','flowchart TD\n  A["Hello"] --> B["World"]');
test('new workspace round-trips its complete schema',()=>{const w=C.newWorkspace([make()]);assert.deepEqual(C.validateWorkspace(w),w)});
test('new documents have separate state',()=>{const a=make(),b=make();a.tags.push('new');assert.equal(b.tags.length,0);assert.notEqual(a.id,b.id)});
test('line endings normalize',()=>assert.equal(C.validateDoc({...make(),source:'a\r\nb\rc'}).source,'a\nb\nc'));
test('null appearance uses safe defaults',()=>assert.deepEqual(C.validateDoc({...make(),visual:null}).visual,C.visualDefaults));
test('unrecognized workspace cannot replace working data',()=>assert.throws(()=>C.validateWorkspace({format:'other'}),/not a MERMAID/));
test('future schema fails explicitly',()=>assert.throws(()=>C.validateWorkspace({...C.newWorkspace(),schema:9}),/Unsupported workspace schema/));
test('oversize source is rejected rather than truncated',()=>assert.throws(()=>C.validateDoc({...make(),source:'a'.repeat(C.MAX_SOURCE+1)}),/safety limit/));
test('workspace cap enforced on validation',()=>assert.throws(()=>C.validateWorkspace(C.newWorkspace(Array.from({length:101},make))),/at most 100/));
test('merges are atomic at capacity',()=>{const w=C.newWorkspace(Array.from({length:99},make));assert.throws(()=>C.mergeDocs(w,[make(),make()]),/100-diagram/);assert.equal(w.docs.length,99)});
test('duplicate imported identifiers receive new IDs',()=>{const a=make();const w=C.validateWorkspace(C.newWorkspace([a,a]));assert.notEqual(w.docs[0].id,w.docs[1].id)});
test('untrusted extra keys and prototype payloads are discarded',()=>{const d=C.validateDoc(JSON.parse('{"source":"flowchart TD","__proto__":{"polluted":true},"unknown":42}'));assert.equal({}.polluted,undefined);assert.equal(d.unknown,undefined);assert.equal(Object.hasOwn(d,'__proto__'),false)});
test('invalid enums and settings use constrained values',()=>{const w=C.newWorkspace([make()]);w.settings={uiTheme:'javascript:',fontSize:500,split:-1};const s=C.validateWorkspace(w).settings;assert.equal(s.uiTheme,'dark');assert.equal(s.fontSize,22);assert.equal(s.split,25)});
test('notes and evidence survive round trip',()=>{const d=make();d.notes='A note';d.assumptions='A1';d.evidence='E1';d.findings=[{id:'f',text:'Review',severity:'high',confidence:'low',status:'open'}];assert.deepEqual(C.validateDoc(d),d)});
test('snapshots restore structured source and visual settings',()=>{const d=make();const s=C.snapshot(d,'Before');d.source='stateDiagram-v2';d.visual.theme='night';assert.match(s.source,/flowchart/);assert.equal(s.visual.theme,'paper')});
test('baseline retained through snapshot limit',()=>{const d=make();d.baseline=C.snapshot(d,'baseline').id;for(let i=0;i<60;i++)C.snapshot(d,'snap '+i);assert.equal(d.snapshots.length,25);assert.equal(d.snapshots.some(s=>s.id===d.baseline),true)});
test('missing baseline references are cleared',()=>{const d=make();d.baseline='missing';assert.equal(C.validateDoc(d).baseline,null)});
test('type detection skips BOM, front matter and comments',()=>{assert.equal(C.typeOf('\ufeff---\ntitle: Test\n---\n%% comment\nflowchart TD'),'Flowchart');assert.equal(C.typeOf('sequenceDiagram\n'),'Sequence')});
test('Markdown imports multiple blocks without treating text as diagram',()=>{const a=C.parseImport('guide.md','# One\n```mermaid\nflowchart TD\nA-->B\n```\n# Two\n```mermaid\nsequenceDiagram\nA->>B: hi\n```');assert.equal(a.docs.length,2);assert.equal(a.docs[0].title,'One');assert.equal(a.docs[1].title,'Two')});
test('Markdown without fenced Mermaid fails',()=>assert.throws(()=>C.parseImport('a.md','flowchart TD'),/No fenced/));
test('plain source import strips a complete outer fence',()=>assert.equal(C.parseImport('a.mmd','```mermaid\nflowchart TD\n```').docs[0].source,'flowchart TD'));
test('Mermaid Live code JSON import',()=>assert.equal(C.parseImport('x.json','{"code":"flowchart LR"}').docs[0].source,'flowchart LR'));
test('bad and primitive JSON imports fail safely',()=>{for(const value of ['{','null','[]','42'])assert.throws(()=>C.parseImport('x.json',value))});
test('workspaces imported intact without mutation',()=>{const w=C.newWorkspace([make()]);const p=C.parseImport('backup.json',JSON.stringify(w));assert.deepEqual(p.workspace,w)});
test('merge creates independent copies',()=>{const d=make(),w=C.newWorkspace([d]);const added=C.mergeDocs(w,[d]);assert.notEqual(added[0].id,d.id);assert.equal(added[0].title,'A diagram (imported)');added[0].notes='edit';assert.equal(d.notes,'')});
test('simple outline lists explicit declarations',()=>assert.deepEqual(C.simpleNodes('flowchart TD\n A["First"] --> B{"Yes?"}').map(n=>n.id),['A','B']));
test('safe IDs prevent syntax insertion and reserved end',()=>{for(const s of ['end','A --> B','9x','<script>'])assert.throws(()=>C.safeID(s));assert.equal(C.safeID('N_01'),'N_01')});
test('builder escapes quotes and line breaks',()=>{assert.equal(C.nodeLine('N1','Say "hi"\nnow','box'),'    N1["Say #quot;hi#quot; now"]')});
test('source comparison reports insertions/deletions',()=>{const diff=C.diffLines('a\nb\nc','a\nx\nc');assert.equal(diff.filter(x=>x.kind==='add').map(x=>x.text).join(''),'x');assert.equal(diff.filter(x=>x.kind==='remove').map(x=>x.text).join(''),'b')});
test('bounded large-file comparison retains unchanged suffix',()=>{const a=Array(1400).fill('a').join('\n');const diff=C.diffLines('one\n'+a,'two\n'+a);assert.equal(diff.filter(x=>x.kind==='add').length,1);assert.equal(diff.filter(x=>x.kind==='same').length,1400)});
test('HTML escaping protects report fields',()=>assert.equal(C.esc('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
test('download names cannot traverse paths',()=>{assert.doesNotMatch(C.filename('../../hello/world'),/[\/\\]/);assert.doesNotMatch(C.filename('../../hello/world'),/^\./)});
