const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function worker(){const handlers={},cache={addAll:async r=>{cache.requests=r},match:async()=>new Response('cached')},deletions=[],context={URL,Request,Response,fetch:async()=>new Response('network'),caches:{open:async()=>cache,keys:async()=>['unrelated-cache','gsg-mermaid-workbench:/diagrams/:0.9.0','gsg-mermaid-workbench:/elsewhere/:0.9.0'],delete:async x=>deletions.push(x)},self:{registration:{scope:'https://example.invalid/diagrams/'},clients:{claim:async()=>true},addEventListener:(name,cb)=>{handlers[name]=cb}}};vm.runInNewContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),context);return{handlers,cache,deletions};}
test('offline cache lists only existing distribution files',async()=>{const {handlers,cache}=worker();let done;handlers.install({waitUntil:p=>{done=p}});await done;for(const r of cache.requests){const name=new URL(r.url).pathname.replace('/diagrams/','')||'index.html';assert.equal(fs.existsSync(path.join(root,name)),true,name)}});
test('old-cache cleanup does not touch other apps or paths',async()=>{const {handlers,deletions}=worker();let done;handlers.activate({waitUntil:p=>{done=p}});await done;assert.deepEqual(deletions,['gsg-mermaid-workbench:/diagrams/:0.9.0'])});
test('offline handler declines unrelated and private data URLs',()=>{const {handlers}=worker();for(const url of ['https://example.invalid/diagrams/private.json','https://elsewhere.invalid/','https://example.invalid/other/index.html']){let intercepted=false;handlers.fetch({request:new Request(url),respondWith:()=>{intercepted=true}});assert.equal(intercepted,false)}});
test('offline handler serves known application files',async()=>{const {handlers}=worker();let result;handlers.fetch({request:new Request('https://example.invalid/diagrams/index.html'),respondWith:p=>{result=p}});assert.equal(await(await result).text(),'cached')});
test('runtime entry points have no external script or stylesheet dependencies',()=>{for(const f of ['index.html','renderer.html']){const s=fs.readFileSync(path.join(root,f),'utf8');assert.doesNotMatch(s,/<(?:script|link)[^>]+(?:src|href)=["'](?:https?:)?\/\//)}});
test('portable has isolated renderer, source, and license notices',()=>{const s=fs.readFileSync(path.join(root,'MERMAID-Workbench-v1.0.0.html'),'utf8');assert.match(s,/MERMAID_RENDERER_HTML/);assert.match(s,/id="third-party-notices"/);assert.match(s,/Mermaid 11.12.2/);assert.doesNotMatch(s,/<script src=/)});
test('no font binaries are packaged',()=>{function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.isDirectory())walk(path.join(dir,e.name));else assert.doesNotMatch(e.name,/\.(?:woff2?|ttf|otf|eot)$/i)}}walk(root)});
