gitGraph
    commit id: "Starting point"
    branch feature
    checkout feature
    commit id: "First pass"
    commit id: "Add tests"
    checkout main
    commit id: "Documentation"
    merge feature
    commit id: "Release" tag: "v1.0"
