/* MERMAID Workbench — portable, side-effect-free data model. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.WorkbenchCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.0.0', SCHEMA=1, MAX_SOURCE=120000, MAX_DOCS=100, MAX_SNAPSHOTS=25;
const defaults={uiTheme:'dark',mode:'easy',layout:'split',sidebar:true,inspector:false,wrap:true,fontSize:14,live:true,grid:true,split:44,sort:'updated',filter:'all',autoFit:true};
const visualDefaults={theme:'paper',look:'classic',curve:'basis',config:'{}'};
const uid=()=>globalThis.crypto?.randomUUID?.()||'d-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);
const now=()=>new Date().toISOString();
function text(v,max=5000,fallback=''){return typeof v==='string'?v.slice(0,max):fallback;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function date(v){return typeof v==='string'&&Number.isFinite(Date.parse(v))?new Date(v).toISOString():now();}
function enumValue(v,options,fallback){return options.includes(v)?v:fallback;}
function clone(v){return JSON.parse(JSON.stringify(v));}
function typeOf(source){const body=source.replace(/^\uFEFF/,'').replace(/^---[\s\S]*?\n---\s*\n/,'').replace(/^\s*%%[^\n]*(\n|$)/gm,'').trim();const header=body.split(/\s/)[0]||'';const types={graph:'Flowchart',flowchart:'Flowchart',sequenceDiagram:'Sequence',classDiagram:'Class','classDiagram-v2':'Class',stateDiagram:'State','stateDiagram-v2':'State',erDiagram:'Entity relationship',gantt:'Gantt',pie:'Pie',mindmap:'Mindmap',journey:'Journey',timeline:'Timeline',gitGraph:'Git graph',quadrantChart:'Quadrant',requirementDiagram:'Requirement',C4Context:'C4 context',C4Container:'C4 container',C4Component:'C4 component','sankey-beta':'Sankey','xychart-beta':'XY chart','block-beta':'Block','packet-beta':'Packet','architecture-beta':'Architecture',kanban:'Kanban','radar-beta':'Radar','treemap-beta':'Treemap',info:'Info'};return types[header]||'Mermaid';}
function visual(v={}){if(!v||typeof v!=='object')v={};return{theme:enumValue(v.theme,['paper','forest','ocean','night','mono'],visualDefaults.theme),look:enumValue(v.look,['classic','handDrawn'],'classic'),curve:enumValue(v.curve,['basis','linear','step','monotoneX'],'basis'),config:text(v.config,15000,'{}')};}
function newDoc(title='Untitled diagram',source='flowchart TD\n    A["Start here"] --> B["Make something clear"]\n',sample=false){return{id:uid(),title,source,created:now(),updated:now(),favorite:false,sample,folder:'',tags:[],notes:'',assumptions:'',evidence:'',findings:[],snapshots:[],baseline:null,visual:clone(visualDefaults),lastValid:null};}
function validateDoc(d){if(!d||typeof d!=='object'||typeof d.source!=='string')throw new Error('Every diagram must contain a Mermaid source string.');if(d.source.length>MAX_SOURCE)throw new Error('A diagram exceeds the 120,000-character safety limit. Split it into smaller diagrams.');const out={id:text(d.id,100)||uid(),title:text(d.title,120,'Untitled diagram').trim()||'Untitled diagram',source:d.source.replace(/\r\n?/g,'\n'),created:date(d.created),updated:date(d.updated),favorite:!!d.favorite,sample:!!d.sample,folder:text(d.folder,80),tags:Array.isArray(d.tags)?d.tags.slice(0,20).map(t=>text(t,40)).filter(Boolean):[],notes:text(d.notes,30000),assumptions:text(d.assumptions,15000),evidence:text(d.evidence,15000),findings:[],snapshots:[],baseline:null,visual:visual(d.visual),lastValid:null};
if(Array.isArray(d.findings))out.findings=d.findings.slice(0,100).filter(f=>f&&typeof f==='object').map(f=>({id:text(f.id,100)||uid(),text:text(f.text,3000),severity:enumValue(f.severity,['info','low','medium','high'],'info'),confidence:enumValue(f.confidence,['low','medium','high'],'medium'),status:enumValue(f.status,['open','resolved'],'open')}));
if(Array.isArray(d.snapshots))out.snapshots=d.snapshots.slice(-MAX_SNAPSHOTS).filter(s=>s&&typeof s.source==='string'&&s.source.length<=MAX_SOURCE).map(s=>({id:text(s.id,100)||uid(),title:text(s.title,120,'Snapshot'),source:s.source,created:date(s.created),visual:visual(s.visual)}));
if(out.snapshots.some(s=>s.id===d.baseline))out.baseline=d.baseline;
if(d.lastValid&&typeof d.lastValid.source==='string'&&d.lastValid.source.length<=MAX_SOURCE)out.lastValid={source:d.lastValid.source,visual:visual(d.lastValid.visual),created:date(d.lastValid.created)};return out;}
function newWorkspace(docs=[]){return{format:'gsg-mermaid-workspace',schema:SCHEMA,appVersion:VERSION,id:uid(),title:'My diagram workspace',revision:uid(),savedAt:now(),active:docs[0]?.id||null,settings:clone(defaults),docs};}
function validateWorkspace(raw){if(!raw||typeof raw!=='object'||raw.format!=='gsg-mermaid-workspace')throw new Error('This is not a MERMAID Workbench workspace. Import .mmd, .mermaid, Markdown, or a Workbench JSON backup.');if(raw.schema!==SCHEMA)throw new Error('Unsupported workspace schema '+String(raw.schema)+'. Open it with a compatible Workbench version; your current workspace was not changed.');if(!Array.isArray(raw.docs)||raw.docs.length>MAX_DOCS)throw new Error('Workspace must contain at most 100 diagrams.');const w=newWorkspace(raw.docs.map(validateDoc));w.id=text(raw.id,100)||uid();w.title=text(raw.title,120,'My diagram workspace');w.revision=text(raw.revision,100)||uid();w.savedAt=date(raw.savedAt);const ids=new Set();w.docs.forEach(d=>{if(ids.has(d.id))d.id=uid();ids.add(d.id)});w.active=ids.has(raw.active)?raw.active:w.docs[0]?.id||null;const s=raw.settings||{};w.settings={uiTheme:enumValue(s.uiTheme,['dark','light','contrast'],'dark'),mode:enumValue(s.mode,['easy','advanced'],'easy'),layout:enumValue(s.layout,['split','source','preview'],'split'),sidebar:typeof s.sidebar==='boolean'?s.sidebar:true,inspector:!!s.inspector,wrap:s.wrap!==false,fontSize:Math.max(11,Math.min(22,Number(s.fontSize)||14)),live:s.live!==false,grid:s.grid!==false,split:Math.max(25,Math.min(70,Number(s.split)||44)),sort:enumValue(s.sort,['updated','title','type'],'updated'),filter:enumValue(s.filter,['all','favorites'],'all'),autoFit:s.autoFit!==false};return w;}
function snapshot(doc,title){const snap={id:uid(),title:text(title,120)||'Snapshot',source:doc.source,created:now(),visual:clone(doc.visual)};doc.snapshots.push(snap);while(doc.snapshots.length>MAX_SNAPSHOTS){let i=doc.snapshots.findIndex(s=>s.id!==doc.baseline);doc.snapshots.splice(i<0?0:i,1);}return snap;}
function parseImport(name,content){if(content.length>12000000)throw new Error('Import is limited to 12 MB.');const ext=name.toLowerCase().split('.').pop();const title=name.replace(/\.[^.]+$/,'');if(ext==='json'){let raw;try{raw=JSON.parse(content)}catch{throw new Error('Invalid JSON. The current workspace has not been changed.')}if(!raw||Array.isArray(raw)||typeof raw!=='object')throw new Error('JSON import must be an object.');if(raw.format==='gsg-mermaid-workspace')return{kind:'workspace',workspace:validateWorkspace(raw),docs:validateWorkspace(raw).docs};if(typeof raw.code==='string')return{kind:'diagrams',docs:[validateDoc({...newDoc(title),source:raw.code})]};if(typeof raw.source==='string')return{kind:'diagrams',docs:[validateDoc({...newDoc(title),...raw})]};throw new Error('Unrecognized JSON format. Expected a workspace, a diagram with source, or Mermaid Live code.');}
if(ext==='md'||ext==='markdown'){const docs=[];const re=/^( {0,3})(`{3,}|~{3,})mermaid[^\n]*\n([\s\S]*?)^\1\2[ \t]*$/gmi;let m;while((m=re.exec(content))){const headings=content.slice(0,m.index).match(/^#{1,6}\s+(.+)$/gm);const heading=headings?.at(-1)?.replace(/^#+\s+/,'');docs.push(validateDoc(newDoc(heading||`${title} · ${docs.length+1}`,m[3].replace(/\n$/,''))));if(docs.length>MAX_DOCS)throw new Error('Too many Mermaid blocks in this file.');}if(!docs.length)throw new Error('No fenced Mermaid code blocks were found in this Markdown file.');return{kind:'diagrams',docs};}
if(!['mmd','mermaid','txt'].includes(ext))throw new Error('Supported imports: .mmd, .mermaid, .md, .markdown, .txt, .json, and Workbench-exported .svg.');let body=content.replace(/^\uFEFF/,'');const fence=body.trim().match(/^```mermaid[^\n]*\n([\s\S]*?)\n```$/i);if(fence)body=fence[1];return{kind:'diagrams',docs:[validateDoc(newDoc(title,body))]};}
function mergeDocs(workspace,docs){if(workspace.docs.length+docs.length>MAX_DOCS)throw new Error('This would exceed the 100-diagram workspace limit. Export a backup and start a separate workspace.');const added=docs.map(d=>{const n=validateDoc(d);n.id=uid();n.sample=false;if(workspace.docs.some(x=>x.title===n.title))n.title+=' (imported)';return n;});workspace.docs.push(...added);workspace.active=added[0]?.id||workspace.active;return added;}
function simpleNodes(source){if(typeOf(source)!=='Flowchart')return[];const result=new Map();source.split('\n').forEach((line,i)=>{const clean=line.replace(/%%.*$/,'');const re=/\b([A-Za-z_][A-Za-z0-9_]*)\s*(\[\[?|\(\(?|\{\{?|>)([^\]\)\}\n]+)[\]\)\}]/g;let m;while((m=re.exec(clean))){if(['subgraph','classDef','style'].includes(m[1]))continue;result.set(m[1],{id:m[1],label:m[3].replace(/^["']|["']$/g,'').replace(/<[^>]*>/g,''),line:i+1});}});return[...result.values()];}
function safeLabel(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'#quot;').replace(/[\r\n]+/g,' ').trim().slice(0,300);}
function safeID(s){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(s)||['end','subgraph','class','style','click'].includes(s))throw new Error('Use an ID starting with a letter or underscore, followed by letters, numbers, or underscores; avoid reserved words.');return s;}
function nodeLine(id,label,shape){id=safeID(id);label=safeLabel(label||id);const pairs={box:['["','"]'],rounded:['("','")'],decision:['{"','"}'],database:['[("','")]'],circle:['(("','"))'],subroutine:['[["','"]]']};const pair=pairs[shape]||pairs.box;return`    ${id}${pair[0]}${label}${pair[1]}`;}
function diffLines(before,after){const a=before.split('\n'),b=after.split('\n');if(a.length*b.length>1500000){let start=0;while(start<a.length&&start<b.length&&a[start]===b[start])start++;let end=0;while(end<a.length-start&&end<b.length-start&&a[a.length-end-1]===b[b.length-end-1])end++;return[...a.slice(0,start).map(t=>({kind:'same',text:t})),...a.slice(start,a.length-end).map(t=>({kind:'remove',text:t})),...b.slice(start,b.length-end).map(t=>({kind:'add',text:t})),...a.slice(a.length-end).map(t=>({kind:'same',text:t}))];}const dp=Array.from({length:a.length+1},()=>new Uint32Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,out=[];while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){out.push({kind:'same',text:a[i++]});j++;}else if(j<b.length&&(i===a.length||dp[i][j+1]>=dp[i+1][j]))out.push({kind:'add',text:b[j++]});else out.push({kind:'remove',text:a[i++]});}return out;}
function filename(s){return(s||'diagram').normalize('NFKC').replace(/[^\p{L}\p{N} ._-]/gu,'-').replace(/\s+/g,'-').replace(/^\.+/,'').slice(0,100)||'diagram';}
return{VERSION,SCHEMA,MAX_SOURCE,MAX_DOCS,MAX_SNAPSHOTS,defaults,visualDefaults,uid,now,text,esc,clone,typeOf,newDoc,newWorkspace,validateDoc,validateWorkspace,snapshot,parseImport,mergeDocs,simpleNodes,safeLabel,safeID,nodeLine,diffLines,filename};
});
